export interface Theme {
  name: string;
  description: string;
  colors: {
    primary: string;      // Main accent (borders, highlights)
    secondary: string;    // Secondary accent (banner, headings)
    muted: string;        // Dimmed text (hints, timestamps)
    text: string;         // Normal text
    userInput: string;    // User input text
    response: string;     // AI response marker
    tool: string;         // Tool call text
    toolResult: string;   // Tool result text
    error: string;        // Error messages
    success: string;      // Success messages
    warning: string;      // Warning/approval prompts
    spinner: string;      // Spinner color
    border: string;       // Border color
    suggestion: string;   // Highlighted suggestion
  };
}

export const THEMES: Record<string, Theme> = {
  "cyberpunk-neon": {
    name: "Cyberpunk Neon",
    description: "Electric cyan & magenta — Night City terminal",
    colors: {
      primary: "#00FFFF",
      secondary: "#FF00FF",
      muted: "#008B8B",
      text: "",
      userInput: "#008B8B",
      response: "#00FFFF",
      tool: "#FF00FF",
      toolResult: "#008B8B",
      error: "red",
      success: "#00FF00",
      warning: "#FF8C00",
      spinner: "#00FFFF",
      border: "#00FFFF",
      suggestion: "#FF00FF",
    },
  },
  dracula: {
    name: "Dracula",
    description: "Dark purple tones",
    colors: {
      primary: "#BD93F9",
      secondary: "#FF79C6",
      muted: "#6272A4",
      text: "#F8F8F2",
      userInput: "#8BE9FD",
      response: "#BD93F9",
      tool: "#FF79C6",
      toolResult: "#6272A4",
      error: "#FF5555",
      success: "#50FA7B",
      warning: "#FFB86C",
      spinner: "#BD93F9",
      border: "#BD93F9",
      suggestion: "#FF79C6",
    },
  },
  gruvbox: {
    name: "Gruvbox",
    description: "Warm retro tones",
    colors: {
      primary: "#FE8019",
      secondary: "#FABD2F",
      muted: "#928374",
      text: "#EBDBB2",
      userInput: "#83A598",
      response: "#FE8019",
      tool: "#FABD2F",
      toolResult: "#928374",
      error: "#FB4934",
      success: "#B8BB26",
      warning: "#FABD2F",
      spinner: "#FE8019",
      border: "#FE8019",
      suggestion: "#FABD2F",
    },
  },
  nord: {
    name: "Nord",
    description: "Cool arctic blues",
    colors: {
      primary: "#88C0D0",
      secondary: "#81A1C1",
      muted: "#4C566A",
      text: "#ECEFF4",
      userInput: "#88C0D0",
      response: "#81A1C1",
      tool: "#5E81AC",
      toolResult: "#4C566A",
      error: "#BF616A",
      success: "#A3BE8C",
      warning: "#EBCB8B",
      spinner: "#88C0D0",
      border: "#81A1C1",
      suggestion: "#88C0D0",
    },
  },
  mono: {
    name: "Mono",
    description: "Clean monochrome — easy on the eyes",
    colors: {
      primary: "#AAAAAA",
      secondary: "#FFFFFF",
      muted: "#666666",
      text: "#CCCCCC",
      userInput: "#AAAAAA",
      response: "#FFFFFF",
      tool: "#CCCCCC",
      toolResult: "#666666",
      error: "#FF6666",
      success: "#66FF66",
      warning: "#FFAA66",
      spinner: "#AAAAAA",
      border: "#888888",
      suggestion: "#FFFFFF",
    },
  },
  solarized: {
    name: "Solarized",
    description: "Solarized dark",
    colors: {
      primary: "#268BD2",
      secondary: "#2AA198",
      muted: "#586E75",
      text: "#839496",
      userInput: "#2AA198",
      response: "#268BD2",
      tool: "#B58900",
      toolResult: "#586E75",
      error: "#DC322F",
      success: "#859900",
      warning: "#CB4B16",
      spinner: "#268BD2",
      border: "#268BD2",
      suggestion: "#2AA198",
    },
  },
  hacker: {
    name: "Hacker",
    description: "Green on black — classic terminal",
    colors: {
      primary: "#00FF00",
      secondary: "#00CC00",
      muted: "#006600",
      text: "#00DD00",
      userInput: "#00FF00",
      response: "#00FF00",
      tool: "#00CC00",
      toolResult: "#006600",
      error: "#FF0000",
      success: "#00FF00",
      warning: "#FFFF00",
      spinner: "#00FF00",
      border: "#00FF00",
      suggestion: "#00CC00",
    },
  },
  catppuccin: {
    name: "Catppuccin",
    description: "Soothing pastel — Mocha flavor",
    colors: {
      primary: "#CBA6F7",
      secondary: "#F5C2E7",
      muted: "#6C7086",
      text: "#CDD6F4",
      userInput: "#89DCEB",
      response: "#CBA6F7",
      tool: "#F5C2E7",
      toolResult: "#6C7086",
      error: "#F38BA8",
      success: "#A6E3A1",
      warning: "#FAB387",
      spinner: "#CBA6F7",
      border: "#CBA6F7",
      suggestion: "#F5C2E7",
    },
  },
  "tokyo-night": {
    name: "Tokyo Night",
    description: "Rain-soaked Shibuya — neon signs in the dark",
    colors: {
      primary: "#FF7AC6",
      secondary: "#7DCFFF",
      muted: "#3B4261",
      text: "#A9B1D6",
      userInput: "#FF9E64",
      response: "#FF7AC6",
      tool: "#7DCFFF",
      toolResult: "#3B4261",
      error: "#F7768E",
      success: "#73DACA",
      warning: "#FF9E64",
      spinner: "#FF7AC6",
      border: "#FF7AC6",
      suggestion: "#7DCFFF",
    },
  },
  "one-dark": {
    name: "One Dark",
    description: "Atom editor classic",
    colors: {
      primary: "#61AFEF",
      secondary: "#C678DD",
      muted: "#5C6370",
      text: "#ABB2BF",
      userInput: "#56B6C2",
      response: "#61AFEF",
      tool: "#C678DD",
      toolResult: "#5C6370",
      error: "#E06C75",
      success: "#98C379",
      warning: "#E5C07B",
      spinner: "#61AFEF",
      border: "#61AFEF",
      suggestion: "#C678DD",
    },
  },
  "rose-pine": {
    name: "Rosé Pine",
    description: "Elegant dark florals",
    colors: {
      primary: "#EBBCBA",
      secondary: "#C4A7E7",
      muted: "#6E6A86",
      text: "#E0DEF4",
      userInput: "#9CCFD8",
      response: "#EBBCBA",
      tool: "#C4A7E7",
      toolResult: "#6E6A86",
      error: "#EB6F92",
      success: "#31748F",
      warning: "#F6C177",
      spinner: "#EBBCBA",
      border: "#EBBCBA",
      suggestion: "#C4A7E7",
    },
  },

  synthwave: {
    name: "Synthwave",
    description: "Retro 80s sunset — outrun aesthetics",
    colors: {
      primary: "#F92AAD",
      secondary: "#E9F501",
      muted: "#614D85",
      text: "#F4EEFF",
      userInput: "#36F9F6",
      response: "#F92AAD",
      tool: "#E9F501",
      toolResult: "#614D85",
      error: "#FE4450",
      success: "#72F1B8",
      warning: "#FF7F11",
      spinner: "#F92AAD",
      border: "#F92AAD",
      suggestion: "#36F9F6",
    },
  },
  "blood-moon": {
    name: "Blood Moon",
    description: "Dark crimson — for the night coders",
    colors: {
      primary: "#FF4444",
      secondary: "#CC2936",
      muted: "#5C2626",
      text: "#E0C4C4",
      userInput: "#FF6B6B",
      response: "#FF4444",
      tool: "#CC2936",
      toolResult: "#5C2626",
      error: "#FF0000",
      success: "#4CAF50",
      warning: "#FF8C00",
      spinner: "#FF4444",
      border: "#FF4444",
      suggestion: "#CC2936",
    },
  },

  "hot-dog": {
    name: "Hot Dog",
    description: "Cursed ketchup & mustard — you asked for it",
    colors: {
      primary: "#FF0000",
      secondary: "#FFFF00",
      muted: "#AA6600",
      text: "#FFFF00",
      userInput: "#FF0000",
      response: "#FFFF00",
      tool: "#FF6600",
      toolResult: "#AA6600",
      error: "#FF0000",
      success: "#00FF00",
      warning: "#FFFF00",
      spinner: "#FF0000",
      border: "#FF0000",
      suggestion: "#FFFF00",
    },
  },
  acid: {
    name: "Acid",
    description: "Every color at once — sensory overload",
    colors: {
      primary: "#FF00FF",
      secondary: "#00FF88",
      muted: "#FF6B00",
      text: "#FFFF00",
      userInput: "#00FFFF",
      response: "#FF3399",
      tool: "#33FF00",
      toolResult: "#FF6B00",
      error: "#FF0044",
      success: "#00FF66",
      warning: "#FFD700",
      spinner: "#BF00FF",
      border: "#FF00AA",
      suggestion: "#00FFCC",
    },
  },
};

export const DEFAULT_THEME = "nord";

export function getTheme(name: string): Theme {
  return THEMES[name] ?? THEMES[DEFAULT_THEME];
}

export function listThemes(): string[] {
  return Object.keys(THEMES);
}
